batch_size: 200
epochs: 200
eval_every_n_epochs: 2
fine_tune_from: "/"
log_every_n_steps: 2
learning_rate: 1e-06
betas: (0.9, 0.98)
eps: 1e-06
weight_decay: 0.0001
num_warmup_steps: 20
num_stable_steps: 140
num_decay_steps: 40
min_lr_ratio: 1e-09
num_cycles: 0.5

dataset:
  num_workers: 4
  valid_size: 0.2
  ms_file: "/.mgf"

