batch_size: 330
epochs: 600
eval_every_n_epochs: 2
fine_tune_from: "/Sep06_13-11-29_ubuntu/"
log_every_n_steps: 2
learning_rate: 5e-06
gradient_accumulation_steps: 4
betas: (0.9, 0.98)
eps: 1e-06
weight_decay: 0.001
num_warmup_steps: 60
num_stable_steps: 420
num_decay_steps: 120
min_lr_ratio: 1e-09
num_cycles: 0.5

dataset:
  num_workers: 0
  valid_size: 0.2
  train_ms_file: "/home/xieting/modernbert_eims_intens_rotery_finetune/data/mainlib_train3_match.mgf"
  train_ms_pre_file: "/home/xieting/modernbert_eims_intens_rotery_finetune/data/mainlib_train3_nom_pred_match.mgf"
  valid_ms_file: "/home/xieting/modernbert_eims_intens_rotery_finetune/data/mainlib_valid3_match.mgf"
  valid_ms_pre_file: "/home/xieting/modernbert_eims_intens_rotery_finetune/data/mainlib_valid3_nom_pred_match.mgf"

